# service node type, [DN|CN|LOG]
service-type = "LOG"
data-dir = "./mo-data"

[log]
level = "info"
format = "console"
max-size = 512

[[fileservice]]
name = "SHARED"
backend = "DISK"
data-dir = "mo-data/shared"

[fileservice.cache]
memory-capacity = "512MB"
disk-capacity = "8GB"
disk-path = "mo-data/file-service-cache"

[[fileservice]]
name = "ETL"
backend = "DISK-ETL"

[observability]
status-port = 8001

[logservice]
logservice-port = 33001
logservice-address = "0.0.0.0:33001"
logservice-listen-address = "0.0.0.0:33001"
raft-address = "0.0.0.0:33000"
raft-listen-address = "0.0.0.0:33000"
gossip-address = "0.0.0.0:33002"
gossip-listen-address = "0.0.0.0:33002"
gossip-seed-addresses = ["127.0.0.1:33002"]

[hakeeper-client]
service-addresses = ["127.0.0.1:33001"]
